cluster.name: docker 
#node.master: true
#node.data: true
#discovery.zen.ping.multicast.enabled: false
#discovery.zen.ping.unicast.hosts: ["10.240.34.61:9300"] 
path:
  logs: /data/log
  data: /data/data
  plugins: /elasticsearch/plugins 
  
http.cors.enabled: true  
http.cors.allow-origin: "http://130.211.106.238"

cloud:
	gce:
		project_id: ls-0001 
		zone: europe-west1-c 
discovery:
	type: gce

