cluster.name: elasticsearch 
network.publish_host: ${DOCKER_HOST_IP}
# http://www.markbetz.net/2014/03/18/elasticsearch-discovery-in-ec2/ 
path:
  logs: /data/log
  data: /data/data
  # The plugin DIR can't be in the data volume for plugins added in Dockerfile to work.
  plugins: /elasticsearch/plugins 
  
http.cors.enabled: true
# The following settings should be replaced with an ENV variables but too lazy at moment
http.cors.allow-origin: "http://130.211.106.238"

cloud:
	gce:
		project_id: ls-0001 
		zone: europe-west1-c 
discovery:
	type: gce

